# Generated by Django 4.2.27 on 2025-12-29 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_id', models.IntegerField()),
                ('e_name', models.CharField(max_length=20)),
                ('e_age', models.IntegerField()),
                ('e_email', models.EmailField(max_length=254, unique=True)),
                ('e_contact', models.CharField(max_length=10, unique=True)),
                ('e_description', models.TextField()),
                ('e_img', models.ImageField(blank=True, null=True, upload_to='employees/')),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
